{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f46e93f2",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import math"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "2f3ca32e",
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_variable_data(name, var_type, n, seed):\n",
    "    np.random.seed(seed)\n",
    "    if var_type == 'continuous':\n",
    "        return np.random.normal(loc=0, scale=1, size=n)\n",
    "    elif var_type == 'discrete':\n",
    "        return np.random.choice([0, 1], size=n)\n",
    "    else:\n",
    "        raise ValueError(f\"Unsupported type for variable {name}: {var_type}\")\n",
    "    \n",
    "def apply_dependency(inputs, dep_type, noise_std=0.1):\n",
    "    data = np.zeros_like(inputs[0])\n",
    "\n",
    "    if dep_type == 'linear':\n",
    "        for i, inp in enumerate(inputs):\n",
    "            data += (i + 1) * inp\n",
    "    elif dep_type == 'nonlinear':\n",
    "        for inp in inputs:\n",
    "            data += np.sin(inp) + np.log(np.abs(inp) + 1)\n",
    "    elif dep_type == 'multiplicative':\n",
    "        data = np.ones_like(inputs[0])\n",
    "        for inp in inputs:\n",
    "            data *= inp\n",
    "    elif dep_type == 'conditional':\n",
    "        # expects at least 2 inputs\n",
    "        cond = inputs[0]\n",
    "        base = inputs[1]\n",
    "        data = np.where(cond > 0, base + np.random.normal(0, noise_std, len(cond)),\n",
    "                        np.random.normal(0, 1, len(cond)))\n",
    "    else:\n",
    "        raise ValueError(f\"Unsupported dependency type: {dep_type}\")\n",
    "\n",
    "    return data + np.random.normal(0, noise_std, len(data))\n",
    "\n",
    "def build_synthetic_data(var: dict, dependencies: dict, n_samples=1_000_000, seed=42):\n",
    "    np.random.seed(seed)\n",
    "    df = pd.DataFrame()\n",
    "    \n",
    "    # Track already generated vars\n",
    "    for var_name in var:\n",
    "        if var_name not in dependencies:\n",
    "            df[var_name] = generate_variable_data(var_name, var[var_name], n_samples, seed + hash(var_name) % 1000)\n",
    "\n",
    "    for var_name in dependencies:\n",
    "        inputs = [df[input_var] for input_var in dependencies[var_name]['depends_on']]\n",
    "        dep_type = dependencies[var_name]['type']\n",
    "        raw_output = apply_dependency(inputs, dep_type)\n",
    "\n",
    "        if var[var_name] == 'discrete':\n",
    "            df[var_name] = (raw_output > np.median(raw_output)).astype(int)\n",
    "        else:\n",
    "            df[var_name] = raw_output\n",
    "\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "3b9550b1",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 608, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1936, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/z2/qz6m5y4j7pqdyn1ttndhygmc0000gp/T/ipykernel_48236/1728970892.py\", line 23, in <module>\n",
      "    df.to_parquet(\"synthetic_data.parquet\", index=False)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/util/_decorators.py\", line 333, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/core/frame.py\", line 3118, in to_parquet\n",
      "    return to_parquet(\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py\", line 478, in to_parquet\n",
      "    impl = get_engine(engine)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py\", line 64, in get_engine\n",
      "    return engine_class()\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py\", line 164, in __init__\n",
      "    import_optional_dependency(\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/compat/_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pyarrow/__init__.py\", line 61, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "âœ… Dataset created with shape: (5000000, 8)\n"
     ]
    }
   ],
   "source": [
    "var = {\n",
    "    'X1': 'continuous',\n",
    "    'X2': 'discrete',\n",
    "    'X3': 'continuous',\n",
    "    'X4': 'discrete',\n",
    "    'Y1': 'continuous',\n",
    "    'Y2': 'discrete',\n",
    "    'Y3': 'continuous',\n",
    "    'Y4': 'discrete',\n",
    "}\n",
    "\n",
    "dependencies = {\n",
    "    'Y1': {'depends_on': ['X1', 'X2'], 'type': 'nonlinear'},\n",
    "    'Y2': {'depends_on': ['X3', 'Y1'], 'type': 'conditional'},\n",
    "    'Y3': {'depends_on': ['Y1', 'Y2'], 'type': 'multiplicative'},\n",
    "    'Y4': {'depends_on': ['Y2', 'X4'], 'type': 'linear'}\n",
    "}\n",
    "\n",
    "# Generate data\n",
    "df = build_synthetic_data(var, dependencies, n_samples=5_000_000)\n",
    "\n",
    "# Write to Parquet for efficient downstream processing\n",
    "df.to_parquet(\"synthetic_data.parquet\", index=False)\n",
    "\n",
    "print(\"âœ… Dataset created with shape:\", df.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "36bde42f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n",
      "A module that was compiled using NumPy 1.x cannot be run in\n",
      "NumPy 2.2.3 as it may crash. To support both 1.x and 2.x\n",
      "versions of NumPy, modules must be compiled with NumPy 2.0.\n",
      "Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.\n",
      "\n",
      "If you are a user of the module, the easiest solution will be to\n",
      "downgrade to 'numpy<2' or try to upgrade the affected module.\n",
      "We expect that some modules will need time to support NumPy 2.\n",
      "\n",
      "Traceback (most recent call last):  File \"<frozen runpy>\", line 198, in _run_module_as_main\n",
      "  File \"<frozen runpy>\", line 88, in _run_code\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "    app.start()\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "    self.io_loop.start()\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 608, in run_forever\n",
      "    self._run_once()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py\", line 1936, in _run_once\n",
      "    handle._run()\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/events.py\", line 84, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "    await self.process_one()\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "    await dispatch(*args)\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "    await result\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "    await super().execute_request(stream, ident, parent)\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "    reply_content = await reply_content\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "    res = shell.run_cell(\n",
      "  File \"/Users/Aaqib/Library/Python/3.11/lib/python/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "    return super().run_cell(*args, **kwargs)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n",
      "    result = self._run_cell(\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n",
      "    result = runner(coro)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n",
      "    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n",
      "    if await self.run_code(code, result, async_=asy):\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"/var/folders/z2/qz6m5y4j7pqdyn1ttndhygmc0000gp/T/ipykernel_48236/1577657866.py\", line 1, in <module>\n",
      "    pd.read_parquet('synthetic_data_new.parquet').count()  # Display the first few rows of the generated dataset\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py\", line 653, in read_parquet\n",
      "    impl = get_engine(engine)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py\", line 64, in get_engine\n",
      "    return engine_class()\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/io/parquet.py\", line 164, in __init__\n",
      "    import_optional_dependency(\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pandas/compat/_optional.py\", line 135, in import_optional_dependency\n",
      "    module = importlib.import_module(name)\n",
      "  File \"/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"/opt/homebrew/lib/python3.11/site-packages/pyarrow/__init__.py\", line 61, in <module>\n",
      "    import pyarrow.lib as _lib\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "_ARRAY_API not found",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[0;31mAttributeError\u001b[0m: _ARRAY_API not found"
     ]
    },
    {
     "data": {
      "text/plain": [
       "X1    5000000\n",
       "X2    5000000\n",
       "X3    5000000\n",
       "X4    5000000\n",
       "Y1    5000000\n",
       "Y2    5000000\n",
       "Y3    5000000\n",
       "Y4    5000000\n",
       "dtype: int64"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "pd.read_parquet('synthetic_data_new.parquet').count()  # Display the first few rows of the generated dataset"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
